---
title: "Metas para 2022"
author: "BAAVdeR"
date: "03/01/2022"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introdução

Bom dia, tudo bem? Este documento está sendo criado a partir de duas motivações principais. A primeira é a **definição de metas** para serem cumpridas no ano de 2022, sendo algumas qualitativas e outras quantitativas. Já a outra motivação é **iniciar o uso do RMarkdown**.

## Apresentação do problema

Os anos passam rápido e dificultam a percepção sobre nosso caminhar ao longo do tempo. Esse documento guiará parte desse processo. As minhas metas para 2022 são basicamente sobre saúde, seja física ou mental.

## Objetivos

1. [Controle financeiro](#id1)
2. [Alimentação](#id2)
3. [Atividade física](#id3)
4. [Leitura](#id4)
5. [Estudo e Profissional](#id5) 

<a id="id1"></a>

### Controle financeiro 

Devido a minha atual ocupação, tanto a receita quanto os gastos são muito instáveis ao longo dos meses. Um controle sobre a parte financeira é uma parte fundamental para manutenção da minha saúde mental. 

* Montar [planilha de gastos diários](https://docs.google.com/spreadsheets/d/1vnSdO5k7gJDuO8ldHofajk2m83iihLx31MS_UCfw0Z0/edit#gid=679917931)
  * Os valores brutos e porcentagens destinados a cada categoria de gastos, serão definidos posteriormente. Possivelmente o gastos mensais serão estabilizados em R$1500,00.
  * Nessa planilha os gastos serão separados por categoria, possibilitando um melhor controle sobre o **destino do dinheiro**.
    * Para facilitar, será uma planilha anual. Sendo possivel acessar o dashboard [mensal](https://docs.google.com/spreadsheets/d/1vnSdO5k7gJDuO8ldHofajk2m83iihLx31MS_UCfw0Z0/edit#gid=2049308682) e [anual](https://docs.google.com/spreadsheets/d/1vnSdO5k7gJDuO8ldHofajk2m83iihLx31MS_UCfw0Z0/edit#gid=1528973642) sobre os gastos.

<a id="id2"></a>

### Alimentação 

A alimentação é um dos pilares para a saúde.

* Acompanhamento com um "bom" nutricionista
* Redução do consumo de
  * açúcar (uma vez por semana)
  * alimentos ultraprocessados (uma vez por mês)
  * carne e derivados (duas vezes por semana)
  * Bebidas alcóolicas (uma vez por semana)

<a id="id3"></a>

### Atividade física 

Com a minha rotina maluca no atual trabalho, é difícil manter uma rotina de exercícios. Para isso tentarei realizar alguns que podem ser realizados em um quarto de hotel. Farei atividades físicas 5 vezes por semana. Enquanto não tenho um acompanhamento profissional irei fazer uma lista de exercícios/metas (e objetivos até o dia 1º de junho)

* Abdominal tradicional (3x20)
* Abdominal infra (3x20)
* Abdominal membros inferiores 90° (3x20)
* Abdominal cruzado (3x20)
* Flexão (4x10)
* Agachamento (3x12)
* Pancha frontal (4x30s)
* Pranchas laterais (4x30s)
* Tríceps no banco (3x12)
* Caminhada/corrida (somatório de 400 km. Correr 5km em 30 minutos). [Acesso ao progresso](https://docs.google.com/spreadsheets/d/1vnSdO5k7gJDuO8ldHofajk2m83iihLx31MS_UCfw0Z0/edit#gid=870953973)
* Perder 2kg/mês (10kg) [Acesso ao progresso](https://docs.google.com/spreadsheets/d/1vnSdO5k7gJDuO8ldHofajk2m83iihLx31MS_UCfw0Z0/edit#gid=1068462443)

<a id="id4"></a>

### Leitura 

Nunca tive esse hábito sempre li por um tempo e parei, então começarei com uma meta de 12 livros. Farei um resumo sobre os Livros no [Medium](https://medium.com/@resendebryan)

1. [_Big Tech_: A ascenção dos dados e a morte da política - Evgeny Morozov](#id6)
2. [(Im)Perfeição - Helena Souza](#id7)
3. [Armas, Germes e aço: Os destinos das sociedades humanas - Jared Diamond](#id8)
4. [10% Humano: Como Os Micro-organismos São A Chave Para A Saúde Do Corpo E Da Mente - Alanna Collen](#id9)
5. [Despertar: Trilogia Xenogênese vol.1 - Octavia E. Butler](#id10)
6. [Ritos de Passagem: Trilogia Xenogênese vol.2 - Octavia E. Butler](#id11)
7. [IMAGO: Trilogia Xenogênese vol.3 - Octavia E. Butler](#id12)
8. [O feminismo é para todo mundo: Políticas arrebatadoras - bell hooks](#id13)
9. [O mundo até ontem: O que podemos aprender com a sociedades tradicionais? - Jared Diamond](#id14)
10. [O Clã dos magos: A trilogia do Mago Negro - Trudi Canavan](#id15)
11. [?](#id16)
12. [?](#id17)

<a id="id5"></a>

### Estudo e profissional 

Pretendo desenvolver várias habilidades em programação. Focarei, sempre que possível, os estudos em problemas envolvendo biotecnologia (em especial, a microbiologia molecular). Para isso, utilizarei bastante o Databricks. A lista de habilidades/ferramentas a serem desenvolvidas serão:

- Liguagens
  - Python
    - PySpark
  - R
  - SQL
    - Oracle
    - SQL Server ou MySQL
- Azure
  - Synapse Analytics
  - Data Factory
  - Data Lake
  - Databricks
- Apache
  - Kafka
  - Hadoop
  - AirFlow
- Power BI ou Tableau (para _data_ _visualization_)
- Coleta de dados
  - Raspagem de dados/ _Web scraping_
  - Uso de APIs
- Git
- GitHub
- RMarkDown
- ETL (extração, tratamento e disponibilização de dados)
- Pipeline de dados

Junto disso, estou participando de dois _bootcamp_ (com encerramento em fevereiro e março). Estou participando desse evento para facilitar o desenvolvimento de algumas habilidades.
Por enquanto, estudarei os seguintes livros para melhorar minhas habilidades em R, banco de dados e estatística.

* R para _Data Science_ - Wickham & Grolemund
* Estatística prática para Cientistas de Dados - Peter Bruce & Andrew Bruce
* Introdução à linguagem SQL - Nield


Sobre a questão profissional, pretendo me manter no atual emprego até agosto. Até lá, vou desenvolver outras habilidades e tentar migrar para vagas envolvendo big data. No momento, meu desejo de mudar de área tem como principal motivador a procura por trabalhos com melhores condições empregatícias. Ao final de 2022, espero estar contratado em regime CLT já na área de tecnologia ou biotecnologia (mesmo sem pretenção salarial melhor que o meu atual cargo).

Em relação a qual área seguir dentro da tecnologia, pensei inicialmente em analista de dados, com estudo, tenho me interessado por outras atividades relacionadas à _Big data_. No momento, as que mais me atraem são a área de engenharia de dados e a área de ciência de dados.

Estou estudando as melhores opções sobre migrar para essas áreas, seja um curso de pós-graduação, algum outro curso de escolas virtuais (alura, udemy, data science academy _etc_).

Outro ponto educacional que quero desenvolver é melhorar o inglês e talvez começar estudos em outra língua (alemão, francês ou espanhol). Minha meta para esse ano é terminar o curso do Duolingo de inglês e fazer algumas aulas de conversação e gramática (possivelmente pelo Duolingo).


### Comentários sobre os livros

1. [_Big Tech_: A ascenção dos dados e a morte da política - Evgeny Morozov]()

<a id="id6"></a>

2. [(Im)Perfeição - Helena Souza]()

<a id="id7"></a>

3. [Armas, Germes e aço: Os destinos das sociedades humanas - Jared Diamond]()

<a id="id8"></a>

4. [10% Humano: Como Os Micro-organismos São A Chave Para A Saúde Do Corpo E Da Mente - Alanna Collen]()

<a id="id9"></a>

5. [Despertar: Trilogia Xenogênese vol.1 - Octavia E. Butler]()

<a id="id10"></a>

6. [Ritos de Passagem: Trilogia Xenogênese vol.2 - Octavia E. Butler]()

<a id="id11"></a>

7. [IMAGO: Trilogia Xenogênese vol.3 - Octavia E. Butler]()

<a id="id12"></a>

8. [O feminismo é para todo mundo: Políticas arrebatadoras - bell hooks]()

<a id="id13"></a>

9. [O mundo até ontem: O que podemos aprender com a sociedades tradicionais? - Jared Diamond]()

<a id="id14"></a>

10. [O Clã dos magos: A trilogia do Mago Negro - Trudi Canavan]()

<a id="id15"></a>

11. [?]()

<a id="id16"></a>

12. [?]()

<a id="id17"></a>

## Veja mais em: (ainda em estruturação)

[GitHub](https://github.com/ResendeBryan)

[LinkedIn](https://www.linkedin.com/in/resendebryan/)

[Medium](https://medium.com/@resendebryan)
